### ISSUE TITLE
How to install this in Linux server?

### ISSUE THREAD

**Issue by githubsrinath** [filipeportes/obdserver#1]
Is there any steps to be followed to install this utility on hosted Linux server?

Many thanks
Srinath Rao

**Comment by filipeportes** [comment]
Hi, sorry about this delay. 

probably this project is out-dated by the meteor evolutions, buts is basically following the instalation of meteor: https://www.meteor.com/install

then in the folder of the project runing using:
meteor

**Comment by M-Ahmad-sattar** [comment]
is it possible to get command on live web, without using of PI?

**Comment by filipeportes** [comment]
sorry, I didn't understand, what do you mean by PI?

**Comment by M-Ahmad-sattar** [comment]
I mean Raspberry Pi

**Comment by filipeportes** [comment]
unfortunately not right now, I'm planing to update this and put in heroku, so It will be available online again, but for this moment It's necessary to run it in your environment for tests.

**Comment by M-Ahmad-sattar** [comment]
so How more time u need to fix this server!

**Comment by filipeportes** [comment]
I have no plans for when I'm doing this, suggest you to install meteor and try to run by yourself.

if you have any doubts about how to install meteor and run the code, feel free to ask.

if you need any professional support, email me: omeuefilipe@gmail.com, so we can discuss scopes, values and schedules.

**Comment by M-Ahmad-sattar** [comment]
Sir, i read that code and install meteor too, can u have some guide or some
tutorials! I really don't know how to fix Meteor server, just guide me the
points, Really thankful to you for this kindness!
