### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by Drjacky** [filipeportes/obdserver#2]
Given link: [http://obdserver.meteor.com/OBDReading](http://obdserver.meteor.com/OBDReading) doesn't work anymore.

**Comment by filipeportes** [comment]
the meteor free host are not available anymore, I'll update this with the meteor framework evolutions and migrate to heroku.

**Comment by M-Ahmad-sattar** [comment]
link not working !!! please need help

**Comment by filipeportes** [comment]
meteor.com free hosting are not available anymore, to test it you will need to run in your machine.

**Comment by M-Ahmad-sattar** [comment]
Please just guide a little, where to put this code and how to connect it over OBD? I installed Meteor but really don't know how to run this stuff!
